### ISSUE TITLE
group implementation

### ISSUE THREAD

**Issue by cedricbonhomme** [JARR-aggregator/JARR#23]
We must provide a way to group and hide in the UI feed by a group feature. It's a major feature missing from pyAggregator.

----------------------------------------
- Bitbucket: https://bitbucket.org/cedricbonhomme/jarr/issues/12/
- Originally reported by: François Schmidts
- Originally created at: 2015-07-27

**Comment by jaesivsm** [comment]
I realize now it's the same issue than #21. I should also not that I'm working on an implementation of both that and #22 in a branch https://github.com/jaesivsm/JARR/tree/feature/categories . It's a work in progress but I'm still a bit far from a usable version.

Anyway, we should close that issue.
