### ISSUE TITLE
supporting comments

### ISSUE THREAD

**Issue by jaesivsm** [JARR-aggregator/JARR#26]
As specified here http://www.rssboard.org/rss-specification#ltcommentsgtSubelementOfLtitemgt
sometimes a link for accessing comments on an entry is available, it should be registered and made available in the UI.

**Comment by cedricbonhomme** [comment]
It seems to be related to #20 .

**Comment by jaesivsm** [comment]
@cedricbonhomme Yup, you're absolutely right, I didn't saw #20 passed.
